import type { PriceInRub, UniqueId } from '@panda-lavanda/shared'

import type {
  ContactMethod,
  IOrder,
  IOrderItem,
} from '../orders'

/**
 * Fields required to create one order line. The `id` is generated by the
 * database, so callers (the checkout form) only provide the snapshot + links.
 *
 * This is the **denormalized snapshot** shape: `productName`, `size` and
 * `unitPrice` are copied from the catalog at checkout time (see
 * {@link IOrderItem}).
 */
export interface CreateOrderItemData {
  exemplarId: UniqueId
  productId: UniqueId
  productName: string
  size: IOrderItem['size']
  unitPrice: PriceInRub
  quantity: number
}

/**
 * Fields required to create an order with its lines. The order `id`,
 * `status` (defaults to `new`) and `createdAt` are generated by the database.
 */
export interface CreateOrderData {
  customerName: string
  phone: string
  contactMethod: ContactMethod
  comment?: string
  totalPrice: PriceInRub
  items: CreateOrderItemData[]
}

/**
 * Repository contract for orders.
 *
 * The interface lives in the domain layer; concrete implementations (e.g.
 * Drizzle-backed in `apps/api`, HTTP-backed on the server, server-function RPC
 * on the client) live in the infrastructure / app layers and are injected at
 * the composition root. This keeps the domain independent of any database or
 * transport — mirroring {@link IProductsRepository}.
 */
export interface IOrdersRepository {
  /**
   * Creates an order with its lines (atomic) and returns the persisted order
   * (with the generated `id`, `status` and `createdAt`).
   */
  create(data: CreateOrderData): Promise<IOrder>
  /** Returns a single order by id, or `null` if not found. */
  getById(id: UniqueId): Promise<IOrder | null>
}
