import type {
  ImageUrl,
  Paginated,
  PriceInRub,
  UniqueId,
} from '@panda-lavanda/shared'
import type { IExemplar, IProduct, IProductFilters, Size } from '../products'

/** Partial product fields allowed in an update operation. */
export interface UpdateProductData {
  name?: string
  description?: string
  category?: UniqueId
  images?: ImageUrl[]
  /**
   * Full replacement of the product's exemplars. When provided, the existing
   * exemplars are deleted and these are inserted in their place (atomic). The
   * `id` of every exemplar is regenerated, so callers must not rely on exemplar
   * ids being stable across an update.
   */
  exemplars?: CreateExemplarData[]
}

/** Partial fields for updating an existing exemplar. */
export interface UpdateExemplarData {
  price?: PriceInRub
  inStock?: boolean
  size?: Size
}

/** Fields required to create an exemplar; the id and productId are generated by the database. */
export interface CreateExemplarData {
  price: PriceInRub
  inStock: boolean
  size: Size
}

/** Fields required to create a product along with its exemplars. The product id is generated by the database. */
export interface CreateProductData {
  name: string
  description: string
  category: UniqueId
  images: ImageUrl[]
  exemplars: CreateExemplarData[]
}

/**
 * Repository contract for products.
 *
 * The interface lives in the domain layer; concrete implementations
 * (e.g. Drizzle-backed) live in the infrastructure layer and are injected at
 * the composition root. This keeps the domain independent of any database.
 */
export interface IProductsRepository {
  /** Creates a new product with its exemplars (atomic) and returns it. */
  create(data: CreateProductData): Promise<IProduct>
  /** Returns products matching the given filters, with the total match count. */
  getMany(filters: IProductFilters): Promise<Paginated<IProduct>>
  /** Returns a single product by id, or `null` if not found. */
  getById(id: UniqueId): Promise<IProduct | null>
  /** Permanently deletes a product by id (cascades to exemplars). */
  delete(id: UniqueId): Promise<void>
  /** Updates a product by id; returns the updated product or `null` if missing. */
  update(id: UniqueId, data: UpdateProductData): Promise<IProduct | null>

  /**
   * Returns a single exemplar of a product, or `null` if either the product or
   * the exemplar does not exist.
   */
  getExemplar(productId: UniqueId, exemplarId: UniqueId): Promise<IExemplar | null>
  /**
   * Adds an exemplar to a product. Returns the created exemplar, or `null` if
   * the product does not exist.
   */
  createExemplar(
    productId: UniqueId,
    data: CreateExemplarData,
  ): Promise<IExemplar | null>
  /**
   * Updates an exemplar (partial). Returns the updated exemplar, or `null` if
   * the product or exemplar does not exist. The exemplar `id` is stable.
   */
  updateExemplar(
    productId: UniqueId,
    exemplarId: UniqueId,
    data: UpdateExemplarData,
  ): Promise<IExemplar | null>
  /**
   * Deletes an exemplar. Idempotent: deleting a missing exemplar succeeds (the
   * end state — no row — is the same).
   */
  deleteExemplar(productId: UniqueId, exemplarId: UniqueId): Promise<void>
}
