import type {
  ImageUrl,
  Paginated,
  PriceInRub,
  UniqueId,
} from '@panda-lavanda/shared'
import type { IProduct, IProductFilters, Size } from '../products'

/** Partial product fields allowed in an update operation. */
export interface UpdateProductData {
  name?: string
  description?: string
  category?: UniqueId
  images?: ImageUrl[]
}

/** Fields required to create an exemplar; the id and productId are generated by the database. */
export interface CreateExemplarData {
  price: PriceInRub
  inStock: boolean
  size: Size
}

/** Fields required to create a product along with its exemplars. The product id is generated by the database. */
export interface CreateProductData {
  name: string
  description: string
  category: UniqueId
  images: ImageUrl[]
  exemplars: CreateExemplarData[]
}

/**
 * Repository contract for products.
 *
 * The interface lives in the domain layer; concrete implementations
 * (e.g. Drizzle-backed) live in the infrastructure layer and are injected at
 * the composition root. This keeps the domain independent of any database.
 */
export interface IProductsRepository {
  /** Creates a new product with its exemplars (atomic) and returns it. */
  create(data: CreateProductData): Promise<IProduct>
  /** Returns products matching the given filters, with the total match count. */
  getMany(filters: IProductFilters): Promise<Paginated<IProduct>>
  /** Returns a single product by id, or `null` if not found. */
  getById(id: UniqueId): Promise<IProduct | null>
  /** Permanently deletes a product by id (cascades to exemplars). */
  delete(id: UniqueId): Promise<void>
  /** Updates a product by id; returns the updated product or `null` if missing. */
  update(id: UniqueId, data: UpdateProductData): Promise<IProduct | null>
}
